### ISSUE TITLE
Naming conventions

### ISSUE THREAD

**Issue by jhawlc** [justinmall/MovieQuiz#2]
Your code 

` Private Sub Button1_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Application.Exit()
    End Sub`

Would be better if it used naming conventions: 

` Private Sub btnExit_Click(sender As Object, e As EventArgs) Handles Button1.Click
        Application.Exit()
    End **Sub`**

Try and add this

**Comment by justinmall** [comment]
Apologies, will take care of that next time.
